MiguelRicardo2003/Frontend-Inmobiliaria

src/pages/Home/components/section-4.jsx
src/shared/pricePropieties.jsx
src/shared/tittlePropieties.jsx

Seccion 4 terminada, agregando componentes para precio, titulos y boton de la vista Home.

section-4 finally

---

src/layouts/publicLayout.jsx
src/pages/Services/Service.jsx
src/pages/Services/serviceData.js
tailwind.config.js

avances en la seccion de servicios

avances en servicios

---

src/pages/Services/Service.jsx
src/pages/Services/components/AttentionModal.jsx
src/pages/Services/components/ServiceCard.jsx

Se completó el desarrollo de la vista de servicios para la inmobiliaria, presentando de manera clara y estructurada los servicios ofrecidos a los usuarios.

seccion servicios terminada

---

src/core/routes/appRoutes.jsx
src/pages/Properties/Properties.jsx
src/pages/Properties/components/PropertyCard.jsx
src/pages/Properties/components/PropertyModal.jsx
src/pages/Properties/utils/propertyFilter.js
src/pages/Properties/utils/usePropertyLoader.js
src/shared/data.js

-Correccion en la carga de propiedades
-La resolucion de las propiedades ahora escala a mayor resolucion de pantalla
-Implementacion de Loading para la carga o filtrado de las propiedades

Correcciones en la vista de propiedades

---

src/pages/Home/components/buttonlabelphone.jsx
src/pages/Home/components/section-7.jsx

seccion finalizada

---

package-lock.json
src/pages/Contact/Contact.jsx
src/pages/Contact/components/Form.jsx
src/pages/Contact/components/Map.jsx

se termino de desarrollar la sección de contactanos

seccion contactanos terminada

---

src/pages/About/About.jsx

avance sobre nosotros

---

src/components/share/whatsappButton.jsx
src/core/routes/appRoutes.jsx
src/layouts/publicLayout.jsx
src/pages/Home/Home.jsx
src/pages/Home/components/FeaturedProperty.jsx
src/pages/Home/components/JoinAsAgent.jsx
src/pages/Home/components/buttonlabelphone.jsx
src/pages/Home/components/categories.jsx
src/pages/Home/components/hero.jsx
src/pages/Properties/styles/property-card-grid.css
src/shared/button.jsx
src/shared/featureOfPropieties.jsx
src/shared/pricePropieties.jsx

Estandarización

---

src/pages/Home/components/JoinAsAgent.jsx
src/pages/Home/components/buttonlabelphone.jsx

Changes Render

---

src/components/ui/DashboardHeader.jsx
src/components/ui/NavItem.jsx
src/components/ui/SidebarDashboard.jsx
src/components/ui/ThemeToggle.jsx
src/core/routes/appRoutes.jsx
src/layouts/DashboardLayout.jsx
src/pages/Contact/Contact.jsx
src/pages/Dashboard/Dashboard.jsx
src/pages/Dashboard/components/TasksList.jsx

Avances #1 en la sección del dashboard

avance #1 dashboard

---

src/pages/Login/Login.jsx

Avance #1 en la sección del login

Avance login

---

src/pages/Home/components/ExclusiveProperties.jsx
src/pages/Home/components/FeaturedProperty.jsx
src/shared/featureOfPropieties.jsx

Se hizo el resposive de la seccion de propiedades exclusivas, además, se incluyeron animaciones para algunas cards

Secc:Propiedades Exclusivas

---

src/pages/Login/Login.jsx
src/pages/Register/Register.jsx

Ajustando los avances

---

src/components/ui/DashboardHeader.jsx
src/components/ui/NavItem.jsx
src/components/ui/SidebarDashboard.jsx
src/core/routes/appRoutes.jsx
src/layouts/DashboardLayout.jsx
src/pages/Dashboard/Analytics.jsx
src/pages/Dashboard/Calendar.jsx
src/pages/Dashboard/Clients.jsx
src/pages/Dashboard/Dashboard.jsx
src/pages/Dashboard/Message.jsx
src/pages/Dashboard/Properties.jsx
src/pages/Dashboard/Settings.jsx

avances #2 en la sección del dashboard

Avance #2 en el dashboard

---

index.html
src/components/ui/Input.jsx
src/layouts/publicLayout.jsx

Algunos cambios e implementaciones de componentes generales

Configuraciones e implementaciones generales

---

src/components/ui/Input.jsx
src/pages/Login/Login.jsx
src/pages/Login/components/FormSingIn.jsx
src/pages/Register/Register.jsx
src/pages/Register/components/FormSingUp.jsx

Implementacion de los formularios en forma de vista, tanto para Login como para Registro.

Avance en el desarrollo del login

---

src/pages/Login/components/FormSingIn.jsx
src/pages/Register/components/FormSingUp.jsx

Avance en metodos responsive

---

package-lock.json
package.json
src/pages/Dashboard/Analytics/Analytics.jsx
src/pages/Dashboard/Analytics/components/DynamicChart.jsx
src/pages/Dashboard/Analytics/components/StatCard.jsx
src/pages/Home/components/buttonlabelphone.jsx

Integracion de graficas para la sección de analisis

avance graficos de analisis

---

src/components/ui/Input.jsx
src/pages/Login/Login.jsx
src/pages/Login/components/FormSingIn.jsx

Sección Completada

---

src/core/routes/appRoutes.jsx
src/pages/Dashboard/Dashboard.jsx
src/pages/Dashboard/Home/Home.jsx
src/pages/Dashboard/Home/components/ActivityChart.jsx
src/pages/Dashboard/Home/components/Button.jsx
src/pages/Dashboard/Home/components/Card.jsx
src/pages/Dashboard/Home/components/RecentActivity.jsx
src/pages/Dashboard/Home/components/Stat.jsx
src/pages/Dashboard/Home/components/TasksList.jsx

se avanzo con la seccion inicio del dashboard

avances en el inicio dashboard

---

package-lock.json
package.json
src/components/ui/Admin/CardAdmin.jsx
src/components/ui/Admin/StatCard.jsx
src/components/ui/Button.jsx
src/components/ui/DashboardHeader/DashboardHeader.jsx
src/components/ui/common/ThemeToggle.jsx
src/hooks/useFilteredUsers.js
src/pages/Dashboard/Admin/Clients/Clients.jsx
src/pages/Dashboard/Admin/Clients/components/DeleteConfirmModal.jsx
src/pages/Dashboard/Admin/Clients/components/DeleteSuccessModal.jsx
src/pages/Dashboard/Admin/Clients/components/EditUserModal.jsx
src/pages/Dashboard/Admin/Clients/components/SuccessModal.jsx
src/pages/Dashboard/Admin/Clients/components/UserSearchBar.jsx
src/pages/Dashboard/Admin/Home/components/TasksList.jsx
tailwind.config.js

se desarrollo completamente la vista del cliente en el dashboard del administrador

seccion cliente terminada

---

src/components/ui/ImageUpload.jsx
src/components/ui/Select.jsx
src/pages/Dashboard/Admin/Properties/Properties.jsx
src/pages/Dashboard/Admin/Properties/components/ListColumn.jsx
src/pages/Dashboard/Admin/Properties/components/ProjectBoard.jsx
src/pages/Dashboard/Admin/Properties/components/ProjectsBoard.jsx
src/pages/Dashboard/Admin/Properties/components/PropertyCard.jsx
src/pages/Dashboard/Admin/Properties/components/PropertyTable.jsx

- Se implementó una **tabla profesional y responsiva** para mostrar las propiedades asociadas a la **sede seleccionada**.
- Cada sede mantiene su **propia lista de propiedades**, gestionadas de forma **independiente**.
---
- La tabla muestra información clave de cada propiedad:
- **Nombre**
- **Dirección**
- **Precio**
- **Estado**
- **Acciones rápidas** disponibles por propiedad:
- 👁️ **Ver detalles:** icono de ojo, muestra un `alert` de ejemplo.
- ✏️ **Editar:** icono de lápiz, muestra un `alert` de ejemplo.
- 🗑️ **Eliminar:** icono de basurero, elimina la propiedad de la sede activa.
- Diseño moderno:
- Uso de **iconos Lucide**.
- Layout limpio basado en componente **Card**.
---
- Permite **eliminar propiedades directamente** desde la tabla.
- Las acciones de **ver** y **editar** están …

Revertir todos los cambios hasta 578ce19

---

package-lock.json
package.json
src/pages/Dashboard/Calendar/Calendar.jsx

Avancé en el calendario y como poder implantar  dicha librería

Avance en el calendario
